"""Shared context utilities for CLI commands."""

from pathlib import Path

import typer

from ash.cli.console import error
from ash.config import AshConfig, load_config
from ash.db import Database, init_database

# Model options by provider (ordered by recommendation for cost/speed)
ANTHROPIC_MODELS = [
    (
        "claude-haiku-4-5",
        "Claude Haiku 4.5 (Recommended - fast, cost-effective)",
    ),
    ("claude-sonnet-4-5", "Claude Sonnet 4.5 (More capable, higher cost)"),
    ("claude-opus-4-5", "Claude Opus 4.5 (Most capable, highest cost)"),
]


def get_config(config_path: Path | None = None) -> AshConfig:
    """Load configuration with error handling.

    Args:
        config_path: Optional path to config file.

    Returns:
        Loaded AshConfig.

    Raises:
        typer.Exit: If configuration cannot be loaded.
    """
    try:
        return load_config(config_path)
    except FileNotFoundError:
        error("No configuration found. Run 'ash init' first.")
        raise typer.Exit(1) from None


async def get_database(config: AshConfig) -> Database:
    """Initialize and connect to database.

    Args:
        config: Application configuration.

    Returns:
        Connected database instance.
    """
    db = init_database(database_path=config.memory.database_path)
    await db.connect()
    return db


def generate_config_template() -> str:
    """Generate a config template with current recommended models.

    Returns:
        TOML config template string.
    """
    default_model = ANTHROPIC_MODELS[0][0]  # Haiku
    sonnet_model = ANTHROPIC_MODELS[1][0]  # Sonnet

    return f'''# Ash Configuration
# Generated by: ash init
#
# Fill in your API key below, then run: ash upgrade

# =============================================================================
# API Key (required)
# =============================================================================
# Set here OR use environment variable: export ANTHROPIC_API_KEY=sk-ant-...

[anthropic]
api_key = ""

# =============================================================================
# Models
# =============================================================================
# Haiku (fast, cheap) as default, Sonnet for complex tasks

[models.default]
provider = "anthropic"
model = "{default_model}"
temperature = 0.7
max_tokens = 4096

[models.sonnet]
provider = "anthropic"
model = "{sonnet_model}"
max_tokens = 8192

# =============================================================================
# Skill/Agent Overrides
# =============================================================================
# Override model for skills or agents

[skills.skill-writer]
model = "sonnet"  # Use more capable model for skill creation

# =============================================================================
# Optional: Telegram Integration
# =============================================================================
# Get bot token from @BotFather, user ID from @userinfobot

# [telegram]
# bot_token = ""  # or set TELEGRAM_BOT_TOKEN env var
# allowed_users = ["123456789"]

# =============================================================================
# Optional: Web Search (Brave)
# =============================================================================
# Get API key at: https://brave.com/search/api/

# [brave_search]
# api_key = ""  # or set BRAVE_SEARCH_API_KEY env var

# =============================================================================
# Optional: Semantic Search
# =============================================================================
# Requires OpenAI API key

# [embeddings]
# provider = "openai"
# model = "text-embedding-3-small"
'''
